[package]
name = "hmr"
description = "Hot Module Reploading for Rust"
version = "0.2.1"
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/raviqqe/hmr"

[dependencies]
notify = "8.0.0"

[lints.rust]
missing_docs = "deny"
warnings = "deny"
